# Nome da aplicação
spring.application.name=primeiro-exemplo

# Porta do servidor
server.port=8080

# Caminho do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/mercadinho

# Nome do Usuario de conexao com o banco
spring.datasource.username=postgres

# Senha de conexao com o banco de dados
spring.datasource.password=123456

# Nome do driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracao para indicar o hibernate gerar atualizacoes automaticamente no sistema
spring.jpa.hibernate.ddl-auto=update